### ISSUE TITLE
[error] "Best Practises" does not work

### ISSUE THREAD

**Issue by SerkanSipahi** [ebidel/lighthouse-badge#1]
According the implementation guide on the README.md this seems to be not working:
`<img src="https://lighthouse-badge.appspot.com?score=95&category=Best Practices">`
>category: optional. Specify a report section label (e.g. "PWA", "Perf", "A11y", "Best Practices")

**Comment by ebidel** [comment]
https://lighthouse-badge.appspot.com/?score=95&category=Best%20Practices
works for me.
