### ISSUE TITLE
Images appear to be broken

### ISSUE THREAD

**Issue by JackHowa** [ebidel/lighthouse-badge#4]
![Screen Shot 2020-05-03 at 3 18 46 PM](https://user-images.githubusercontent.com/5950956/80924887-6388d280-8d51-11ea-9096-b158fa0d5a0f.png)

not found https://lighthouse-badge.appspot.com/

**Comment by JackHowa** [comment]
Let me know @ebidel if this is not being supported anymore. It was a good, small feature -- thanks for your work

**Comment by ebidel** [comment]
Yea sorry. Not maintaining this app anymore.

**Comment by JackHowa** [comment]
No worries @ebidel. Sorry to bother
