### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by pke** [ebidel/lighthouse-badge#5]
Searched for existing badges but this site seems to be down.

**Comment by richjava** [comment]
Yes, badges are no longer displaying for me too :(

**Comment by pke** [comment]
Already working on a replacement service for this one ;) It actually runs lighthouse against a site and generates the badge for you.

[https://lighthouse-badge.now.sh/badge?url=https://example.com&category=performance](https://lighthouse-badge.now.sh/badge?url=https%3A%2F%2Fexample.com&category=performance)

Mind you its currently slow and can timeout (after 10s) since its running on a serverless lambda. I'll move it to a dedicated server and add a 24h cache which should improve performance.

**Comment by ebidel** [comment]
Yea, sorry folks. Some of my free GCP projects have finally expired after leaving Google last year. Didn't want to renew or start paying for a better tier. I suggest forking or creating your own custom badge and hosting the image yourself.

**Comment by pke** [comment]
Sure no problem. As I wrote I took your idea as an inspiration for a "live" badge service. I'll soon migrate it to a dedicated server and see how it performs.
